import type { NextPage } from "next";
import Head from "next/head";
import Menu from "../components/Menu";
import Image from "next/image";
import Button from "../components/Button";
import { LinkIcon, TrashIcon } from "@heroicons/react/24/solid";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const router = useRouter();
  return (
    <div className="container mx-auto">
      <Head>
        <title>Apapun</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Menu />

      {/* Header Components */}
      <div className="flex flex-col place-items-center py-44 space-y-5">
        <h1 className="text-5xl font-bold">Yuk Coba Trustly</h1>
        <h2 className="text-lg bg-zinc-100 px-3 py-1">
          Voting Apapun Di Website ? Tinggal Klik
        </h2>
        <Image alt="Header" src={"/clip-voting.gif"} width={274} height={243} />
        <div className="space-x-10 flex">
          <Button
            text="Buat Vote Baru"
            onClick={() => router.push("/vote/create")}
            className="bg-black text-white hover:bg-zinc-800"
          />
          <p className="flex py-3">Atau</p>
          <Button
            text="Ikutan Vote"
            onClick={() => router.push("/participant/")}
            className="hover:bg-black hover:text-white bg-zinc-800 text-white"
          />
        </div>
      </div>
      {/* Header Components */}

      {/* Table Components */}
      <div>
        <p className="py-5 text-lg font-bold">Vote Yang Kamu Buat</p>
        <table className="table-auto w-full border border-zinc-100">
          <thead>
            <tr className="border-b border-zinc-100">
              <th className="p-5 text-left">No</th>
              <th className="p-5 text-left">Judul</th>
              <th className="p-5 text-left">Kandidat</th>
              <th className="p-5 text-left">Kode</th>
              <th className="p-5 text-left">Mulai</th>
              <th className="p-5 text-left">Selesai</th>
            </tr>
          </thead>

          <tbody>
            <tr>
              <td className="p-5 text-left">1</td>
              <td className="p-5 text-left">Judul Voting</td>
              <td className="p-5 text-left">Maman vs Racing</td>
              <td className="p-5 text-left">ISMXCO</td>
              <td className="p-5 text-left">1 Juli 2023 7:00 AM</td>
              <td className="p-5 text-left">2 Juli 2023 17:00 AM</td>
              <td className="p-5 text-left">
                <div>
                  <a href="">
                    <LinkIcon className="w-8 h-8 p-2 hover:bg-zinc-100" />
                  </a>
                  <a href="">
                    <TrashIcon className="w-8 h-8 p-2 hover:bg-zinc-100" />
                  </a>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      {/* Table Components */}
    </div>
  );
};

export default Home;
